name: Phonebook container

services:
  phonebook:
    image: mrieramar993/phonebook:latest
    ports:
      - ${PORT}
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
    container_name: phonebook